<template>
  <div id="main" style="width: 100%;height: 80vh"></div>
</template>

<script>
  export default {
    methods: {
      myEcharts() {
        var myChart = this.$echarts.init(document.getElementById('main'));

        myChart.showLoading();
        var webkitDep = {
          "type": "force",
          "categories": [//关系网类别，可以写多组
            {name: "基础"},       //关系网类别
            {name: "搜索"},
            {name: "动态规划"},
            {name: "字符串"},
            {name: "数学"},
            {name: "数据结构"},
            {name: "图论"},
            {name: "计算几何"},
            {name: "杂项"},
            {name: "思维"}
          ],
          "nodes": [//展示的节点
            {category: 0, name: "基础", 		value: 1000, id: 0},
            {category: 1, name: "搜索", 		value: 3000, id: 1},
            {category: 2, name: "动态规划",	value: 1000, id: 2},
            {category: 3, name: "字符串", 	value: 1000, id: 3},
            {category: 4, name: "数学", 		value: 1000, id: 4},
            {category: 5, name: "数据结构", 	value: 1000, id: 5},
            {category: 6, name: "图论", 		value: 1000, id: 6},
            {category: 7, name: "计算几何", 	value: 1000, id: 7},
            {category: 8, name: "杂项", 		value: 1000, id: 8},
            {category: 9, name: "思维", 		value: 1000, id: 9},
            {category: 0, name: "枚举", 	 value: 1, id: 10},
            {category: 0, name: "模拟", 	 value: 1, id: 11},
            {category: 0, name: "递归&分治", 	 value: 1, id: 12},
            {category: 0, name: "贪心", 	 value: 1, id: 13},
            {category: 0, name: "排序", 	 value: 1, id: 14},
            {category: 0, name: "二分", 	 value: 1, id: 15},
            {category: 0, name: "倍增", 	 value: 1, id: 16},
            {category: 0, name: "构造", 	 value: 1, id: 17},
            {category: 0, name: "前缀和&差分", 	 value: 1, id: 18},
            {category: 1, name: "DFS(搜索)", 	 value: 1, id: 19},
            {category: 1, name: "BFS(搜索)", 	 value: 1, id: 20},
            {category: 1, name: "双向搜索", 	 value: 1, id: 21},
            {category: 1, name: "启发式搜索", 	 value: 1, id: 22},
            {category: 1, name: "A*", 	 value: 1, id: 23},
            {category: 1, name: "迭代加深搜索", 	 value: 1, id: 24},
            {category: 1, name: "IDA*", 	 value: 1, id: 25},
            {category: 1, name: "回溯法", 	 value: 1, id: 26},
            {category: 1, name: "Dancing_Links", 	 value: 1, id: 27},
            {category: 2, name: "记忆化搜索", 	 value: 1, id: 28},
            {category: 2, name: "背包DP", 	 value: 1, id: 29},
            {category: 2, name: "区间DP", 	 value: 1, id: 30},
            {category: 2, name: "DAG上的DP", 	 value: 1, id: 31},
            {category: 2, name: "树形DP", 	 value: 1, id: 32},
            {category: 2, name: "状压DP", 	 value: 1, id: 33},
            {category: 2, name: "数位DP", 	 value: 1, id: 34},
            {category: 2, name: "插头DP", 	 value: 1, id: 35},
            {category: 2, name: "计数DP", 	 value: 1, id: 36},
            {category: 2, name: "动态DP", 	 value: 1, id: 37},
            {category: 2, name: "DP优化", 	 value: 1, id: 38},
            {category: 3, name: "字符串匹配", 	 value: 1, id: 39},
            {category: 3, name: "字符串哈希", 	 value: 1, id: 40},
            {category: 3, name: "字典树(Trie)", 	 value: 1, id: 41},
            {category: 3, name: "前缀函数与KMP算法", 	 value: 1, id: 42},
            {category: 3, name: "Z函数(扩展KMP)", 	 value: 1, id: 43},
            {category: 3, name: "自动机", 	 value: 1, id: 44},
            {category: 3, name: "AC自动机", 	 value: 1, id: 45},
            {category: 3, name: "后缀数组(SA)", 	 value: 1, id: 46},
            {category: 3, name: "后缀自动机(SAM)", 	 value: 1, id: 47},
            {category: 3, name: "广义后缀自动机", 	 value: 1, id: 48},
            {category: 3, name: "后缀树", 	 value: 1, id: 49},
            {category: 3, name: "Manacher", 	 value: 1, id: 50},
            {category: 3, name: "回文树", 	 value: 1, id: 51},
            {category: 3, name: "序列自动机", 	 value: 1, id: 52},
            {category: 3, name: "最小表示法", 	 value: 1, id: 53},
            {category: 3, name: "Lyndon分解", 	 value: 1, id: 54},
            {category: 4, name: "复数", 	 value: 1, id: 55},
            {category: 4, name: "位运算", 	 value: 1, id: 56},
            {category: 4, name: "快速幂", 	 value: 1, id: 57},
            {category: 4, name: "进位制", 	 value: 1, id: 58},
            {category: 4, name: "高精度计算", 	 value: 1, id: 59},
            {category: 4, name: "数论", 	 value: 1, id: 60},
            {category: 4, name: "多项式", 	 value: 1, id: 61},
            {category: 4, name: "线性代数", 	 value: 1, id: 62},
            {category: 4, name: "线性规划", 	 value: 1, id: 63},
            {category: 4, name: "组合数学", 	 value: 1, id: 64},
            {category: 4, name: "概率&期望", 	 value: 1, id: 65},
            {category: 4, name: "置换群", 	 value: 1, id: 66},
            {category: 4, name: "斐波那契数列", 	 value: 1, id: 67},
            {category: 4, name: "博弈论", 	 value: 1, id: 68},
            {category: 4, name: "牛顿迭代法", 	 value: 1, id: 69},
            {category: 4, name: "数值积分", 	 value: 1, id: 70},
            {category: 4, name: "分段打表", 	 value: 1, id: 71},
            {category: 5, name: "栈", 	 value: 1, id: 72},
            {category: 5, name: "队列", 	 value: 1, id: 73},
            {category: 5, name: "链表", 	 value: 1, id: 74},
            {category: 5, name: "哈希表", 	 value: 1, id: 75},
            {category: 5, name: "并查集", 	 value: 1, id: 76},
            {category: 5, name: "并查集时间复杂度证明", 	 value: 1, id: 77},
            {category: 5, name: "堆", 	 value: 1, id: 78},
            {category: 5, name: "块状数据结构", 	 value: 1, id: 79},
            {category: 5, name: "单调栈", 	 value: 1, id: 80},
            {category: 5, name: "单调队列", 	 value: 1, id: 81},
            {category: 5, name: "ST表", 	 value: 1, id: 82},
            {category: 5, name: "树状数组", 	 value: 1, id: 83},
            {category: 5, name: "线段树", 	 value: 1, id: 84},
            {category: 5, name: "区间最值操作&区间历史最值", 	 value: 1, id: 85},
            {category: 5, name: "划分树", 	 value: 1, id: 86},
            {category: 5, name: "二叉搜索树&平衡树", 	 value: 1, id: 87},
            {category: 5, name: "可持久化数据结构", 	 value: 1, id: 88},
            {category: 5, name: "树套树", 	 value: 1, id: 89},
            {category: 5, name: "K-D_Tree", 	 value: 1, id: 90},
            {category: 5, name: "珂朵莉树", 	 value: 1, id: 91},
            {category: 5, name: "动态树", 	 value: 1, id: 92},
            {category: 5, name: "析合树", 	 value: 1, id: 93},
            {category: 6, name: "图的存储", 	 value: 1, id: 94},
            {category: 6, name: "DFS(图论)", 	 value: 1, id: 95},
            {category: 6, name: "BFS(图论)", 	 value: 1, id: 96},
            {category: 6, name: "树上问题", 	 value: 1, id: 97},
            {category: 6, name: "矩阵树定理", 	 value: 1, id: 98},
            {category: 6, name: "有向无环图", 	 value: 1, id: 99},
            {category: 6, name: "拓扑排序", 	 value: 1, id: 100},
            {category: 6, name: "最小生成树", 	 value: 1, id: 101},
            {category: 6, name: "最小树形图", 	 value: 1, id: 102},
            {category: 6, name: "最短路", 	 value: 1, id: 103},
            {category: 6, name: "拆点", 	 value: 1, id: 104},
            {category: 6, name: "差分约束", 	 value: 1, id: 105},
            {category: 6, name: "k短路", 	 value: 1, id: 106},
            {category: 6, name: "连通性相关", 	 value: 1, id: 107},
            {category: 6, name: "2-SAT", 	 value: 1, id: 108},
            {category: 6, name: "欧拉图", 	 value: 1, id: 109},
            {category: 6, name: "哈密顿图", 	 value: 1, id: 110},
            {category: 6, name: "二分图", 	 value: 1, id: 111},
            {category: 6, name: "最小环", 	 value: 1, id: 112},
            {category: 6, name: "平面图", 	 value: 1, id: 113},
            {category: 6, name: "图的着色", 	 value: 1, id: 114},
            {category: 6, name: "网络流", 	 value: 1, id: 115},
            {category: 6, name: "Prufer序列", 	 value: 1, id: 116},
            {category: 6, name: "LGV引理", 	 value: 1, id: 117},
            {category: 6, name: "弦图", 	 value: 1, id: 118},
            {category: 7, name: "二维计算几何基础", 	 value: 1, id: 119},
            {category: 7, name: "三维计算几何基础", 	 value: 1, id: 120},
            {category: 7, name: "极坐标系", 	 value: 1, id: 121},
            {category: 7, name: "距离", 	 value: 1, id: 122},
            {category: 7, name: "Pick定理", 	 value: 1, id: 123},
            {category: 7, name: "三角剖分", 	 value: 1, id: 124},
            {category: 7, name: "凸包", 	 value: 1, id: 125},
            {category: 7, name: "扫描线", 	 value: 1, id: 126},
            {category: 7, name: "旋转卡壳", 	 value: 1, id: 127},
            {category: 7, name: "半平面交", 	 value: 1, id: 128},
            {category: 7, name: "平面最近点对", 	 value: 1, id: 129},
            {category: 7, name: "随机增量法", 	 value: 1, id: 130},
            {category: 7, name: "反演变换", 	 value: 1, id: 131},
            {category: 7, name: "计算几何杂项", 	 value: 1, id: 132},
            {category: 8, name: "读入、输出优化", 	 value: 1, id: 133},
            {category: 8, name: "复杂度", 	 value: 1, id: 134},
            {category: 8, name: "离散化", 	 value: 1, id: 135},
            {category: 8, name: "离线算法", 	 value: 1, id: 136},
            {category: 8, name: "分数规划", 	 value: 1, id: 137},
            {category: 8, name: "随机化", 	 value: 1, id: 138},
            {category: 8, name: "悬线法", 	 value: 1, id: 139},
            {category: 8, name: "计算理论基础", 	 value: 1, id: 140},
            {category: 8, name: "字节顺序", 	 value: 1, id: 141},
            {category: 8, name: "约瑟夫问题", 	 value: 1, id: 142},
            {category: 8, name: "Stern-Brocot树与Farey序列", 	 value: 1, id: 143},
            {category: 8, name: "格雷码", 	 value: 1, id: 144},
            {category: 8, name: "表达式求值", 	 value: 1, id: 145}
          ],
          "links": [//节点之间连接
            {source: 0, target: 1, value: 10},
            {source: 0, target: 2, value: 10},
            {source: 0, target: 3, value: 10},
            {source: 0, target: 4, value: 10},
            {source: 0, target: 7, value: 10},
            {source: 0, target: 5, value: 10},

            {source: 0, target: 9, value: 100},
            {source: 8, target: 9, value: 100},

            {source: 5, target: 8, value: 10},
            {source: 6, target: 8, value: 10},
            {source: 7, target: 8, value: 10},
            {source: 9, target: 8, value: 10},
            {source: 1, target: 8, value: 10},
            {source: 4, target: 8, value: 10},
            {source: 0, target: 8, value: 10},

            {source: 1, target: 2, value: 10},
            {source: 2, target: 3, value: 10},
            {source: 3, target: 4, value: 10},
            {source: 4, target: 5, value: 10},
            {source: 5, target: 6, value: 10},
            {source: 7, target: 6, value: 10},
            {source: 7, target: 1, value: 10},

            {source: 0, target: 10,	 value: 1},
            {source: 0, target: 11,	 value: 1},
            {source: 0, target: 12,	 value: 1},
            {source: 0, target: 13,	 value: 1},
            {source: 0, target: 14,	 value: 1},
            {source: 0, target: 15,	 value: 1},
            {source: 0, target: 16,	 value: 1},
            {source: 0, target: 17,	 value: 1},
            {source: 0, target: 18,	 value: 1},
            {source: 1, target: 19,	 value: 1},
            {source: 1, target: 20,	 value: 1},
            {source: 1, target: 21,	 value: 1},
            {source: 1, target: 22,	 value: 1},
            {source: 1, target: 23,	 value: 1},
            {source: 1, target: 24,	 value: 1},
            {source: 1, target: 25,	 value: 1},
            {source: 1, target: 26,	 value: 1},
            {source: 1, target: 27,	 value: 1},
            {source: 2, target: 28,	 value: 1},
            {source: 2, target: 29,	 value: 1},
            {source: 2, target: 30,	 value: 1},
            {source: 2, target: 31,	 value: 1},
            {source: 2, target: 32,	 value: 1},
            {source: 2, target: 33,	 value: 1},
            {source: 2, target: 34,	 value: 1},
            {source: 2, target: 35,	 value: 1},
            {source: 2, target: 36,	 value: 1},
            {source: 2, target: 37,	 value: 1},
            {source: 2, target: 38,	 value: 1},
            {source: 3, target: 39,	 value: 1},
            {source: 3, target: 40,	 value: 1},
            {source: 3, target: 41,	 value: 1},
            {source: 3, target: 42,	 value: 1},
            {source: 3, target: 43,	 value: 1},
            {source: 3, target: 44,	 value: 1},
            {source: 3, target: 45,	 value: 1},
            {source: 3, target: 46,	 value: 1},
            {source: 3, target: 47,	 value: 1},
            {source: 3, target: 48,	 value: 1},
            {source: 3, target: 49,	 value: 1},
            {source: 3, target: 50,	 value: 1},
            {source: 3, target: 51,	 value: 1},
            {source: 3, target: 52,	 value: 1},
            {source: 3, target: 53,	 value: 1},
            {source: 3, target: 54,	 value: 1},
            {source: 4, target: 55,	 value: 1},
            {source: 4, target: 56,	 value: 1},
            {source: 4, target: 57,	 value: 1},
            {source: 4, target: 58,	 value: 1},
            {source: 4, target: 59,	 value: 1},
            {source: 4, target: 60,	 value: 1},
            {source: 4, target: 61,	 value: 1},
            {source: 4, target: 62,	 value: 1},
            {source: 4, target: 63,	 value: 1},
            {source: 4, target: 64,	 value: 1},
            {source: 4, target: 65,	 value: 1},
            {source: 4, target: 66,	 value: 1},
            {source: 4, target: 67,	 value: 1},
            {source: 4, target: 68,	 value: 1},
            {source: 4, target: 69,	 value: 1},
            {source: 4, target: 70,	 value: 1},
            {source: 4, target: 71,	 value: 1},
            {source: 5, target: 72,	 value: 1},
            {source: 5, target: 73,	 value: 1},
            {source: 5, target: 74,	 value: 1},
            {source: 5, target: 75,	 value: 1},
            {source: 5, target: 76,	 value: 1},
            {source: 5, target: 77,	 value: 1},
            {source: 5, target: 78,	 value: 1},
            {source: 5, target: 79,	 value: 1},
            {source: 5, target: 80,	 value: 1},
            {source: 5, target: 81,	 value: 1},
            {source: 5, target: 82,	 value: 1},
            {source: 5, target: 83,	 value: 1},
            {source: 5, target: 84,	 value: 1},
            {source: 5, target: 85,	 value: 1},
            {source: 5, target: 86,	 value: 1},
            {source: 5, target: 87,	 value: 1},
            {source: 5, target: 88,	 value: 1},
            {source: 5, target: 89,	 value: 1},
            {source: 5, target: 90,	 value: 1},
            {source: 5, target: 91,	 value: 1},
            {source: 5, target: 92,	 value: 1},
            {source: 5, target: 93,	 value: 1},
            {source: 6, target: 94,	 value: 1},
            {source: 6, target: 95,	 value: 1},
            {source: 6, target: 96,	 value: 1},
            {source: 6, target: 97,	 value: 1},
            {source: 6, target: 98,	 value: 1},
            {source: 6, target: 99,	 value: 1},
            {source: 6, target: 100,	 value: 1},
            {source: 6, target: 101,	 value: 1},
            {source: 6, target: 102,	 value: 1},
            {source: 6, target: 103,	 value: 1},
            {source: 6, target: 104,	 value: 1},
            {source: 6, target: 105,	 value: 1},
            {source: 6, target: 106,	 value: 1},
            {source: 6, target: 107,	 value: 1},
            {source: 6, target: 108,	 value: 1},
            {source: 6, target: 109,	 value: 1},
            {source: 6, target: 110,	 value: 1},
            {source: 6, target: 111,	 value: 1},
            {source: 6, target: 112,	 value: 1},
            {source: 6, target: 113,	 value: 1},
            {source: 6, target: 114,	 value: 1},
            {source: 6, target: 115,	 value: 1},
            {source: 6, target: 116,	 value: 1},
            {source: 6, target: 117,	 value: 1},
            {source: 6, target: 118,	 value: 1},
            {source: 7, target: 119,	 value: 1},
            {source: 7, target: 120,	 value: 1},
            {source: 7, target: 121,	 value: 1},
            {source: 7, target: 122,	 value: 1},
            {source: 7, target: 123,	 value: 1},
            {source: 7, target: 124,	 value: 1},
            {source: 7, target: 125,	 value: 1},
            {source: 7, target: 126,	 value: 1},
            {source: 7, target: 127,	 value: 1},
            {source: 7, target: 128,	 value: 1},
            {source: 7, target: 129,	 value: 1},
            {source: 7, target: 130,	 value: 1},
            {source: 7, target: 131,	 value: 1},
            {source: 7, target: 132,	 value: 1},
            {source: 8, target: 133,	 value: 1},
            {source: 8, target: 134,	 value: 1},
            {source: 8, target: 135,	 value: 1},
            {source: 8, target: 136,	 value: 1},
            {source: 8, target: 137,	 value: 1},
            {source: 8, target: 138,	 value: 1},
            {source: 8, target: 139,	 value: 1},
            {source: 8, target: 140,	 value: 1},
            {source: 8, target: 141,	 value: 1},
            {source: 8, target: 142,	 value: 1},
            {source: 8, target: 143,	 value: 1},
            {source: 8, target: 144,	 value: 1},
            {source: 8, target: 145,	 value: 1}
          ]
        };
        myChart.hideLoading();

        var option = {
          legend: {
            data:["基础","搜索", "动态规划","字符串","数学","数据结构","图论","计算几何","杂项"],
          },
          series: [{
            type: 'graph',
            layout: 'force',
            roam: true,
            animation: false,
            label: {
              normal: {
                show:true,
                position: 'right'
              }
            },
            draggable: true,
            data: webkitDep.nodes.map(function (node, idx) {
              node.id = idx;
              return node;
            }),
            categories: webkitDep.categories,
            force: {
              edgeLength: 105,
              repulsion: 100
            },
            edges: webkitDep.links
          }]
        };
        myChart.setOption(option);
        myChart.on('click', (param) => {
          var arrayIndex = param.dataIndex;
          if (param.dataType == 'node') {
            this.$emit('event1', param.name)
          }
        });
      }
    },
    mounted() {
      this.myEcharts();
    }
  }
</script>

<style>

</style>
